### PR TITLE
Innerve Sponsorship Page

### PR DESCRIPTION
**Pull request by jainsakshi10**

### CODE REVIEW

**Comment by lisa761** [comment]
Hey, thanks for submitting this! Can we reduce the timer on the carousal? It seems a little too long. Another thing is that every time the next picture comes in, there seems to be a zoom in for a few seconds before it settles back. It's too fast to capture, but you see how the picture is coming in in a size lot bigger than the final one it settles in? It takes up the whole frame of the carousal before going to the final size and you can see the edges of the carousal again.





Otherwise it looks good!

**Comment by jainsakshi10** [comment]
Ok will work on it!

**Comment by jainsakshi10** [comment]
Hey Lisa! I have made the changes that you had asked. Let me know if its fine or any other modifications are required.
Thanks!

**Review by lisa761 — COMMENTED** [review]
Hey, this looks good. Although can we make the images in carousal responsive? It becomes pretty disproportionate on smaller screen.

**Pull request closed without merging**
